export { DocumentPdfIllustration } from "./DocumentPdfIllustration"
export { DocumentDocxIllustration } from "./DocumentDocxIllustration"
export { DocumentXlxIllustration as DocumentXlsxIllustration } from "./DocumentXlsxIllustration"
export { DocumentCsvIllustration } from "./DocumentCsvIllustration"
export { DocumentPptxIllustration } from "./DocumentPptxIllustration"
export { DocumentTxtIllustration } from "./DocumentTxtIllustration"
export { DocumentJsonIllustration } from "./DocumentJsonIllustration"
export { DocumentZipIllustration } from "./DocumentZipIllustration"
export { DocumentImgIllustration as DocumentPngIllustration } from "./DocumentPngIllustration"
export { DocumentImgIllustration as DocumentJpgIllustration } from "./DocumentJpgIllustration"
